import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: './iransansx/IRANSansXRegular.ttf',

})
export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body className={myFont.className}>

      {children}</body>
    </html>
  );
}
